/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-03-29 03:07:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"headerwrapper\">\r\n");
      out.write("        <div class=\"header-left\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.do\" class=\"logo\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\logo.png\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"pull-right\">\r\n");
      out.write("                <a href=\"\" class=\"menu-collapse\">\r\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- header-left -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-right\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"pull-right\">\r\n");
      out.write("\r\n");
      out.write("                <form class=\"form form-search\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/search-results.do\">\r\n");
      out.write("                    <input type=\"search\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-group btn-group-list btn-group-notification\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("                        <span class=\"badge\">5</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"dropdown-menu pull-right\">\r\n");
      out.write("                        <a href=\"\" class=\"link-right\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("                        <h5>通知</h5>\r\n");
      out.write("                        <ul class=\"media-list dropdown-list\">\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user1.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Nusja Nawancali</strong> likes a photo of you\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-thumbs-up\"></i> 15 minutes ago</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user2.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Weno Carasbong</strong> shared a photo of you in your <strong>Mobile Uploads</strong> album.\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-calendar\"></i> July 04, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user3.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Venro Leonga</strong> likes a photo of you\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-thumbs-up\"></i> July 03, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user4.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Nanterey Reslaba</strong> shared a photo of you in your <strong>Mobile Uploads</strong> album.\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-calendar\"></i> July 03, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user1.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Nusja Nawancali</strong> shared a photo of you in your <strong>Mobile Uploads</strong> album.\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-calendar\"></i> July 02, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"dropdown-footer text-center\">\r\n");
      out.write("                            <a href=\"\" class=\"link\">查看所有通知</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div><!-- dropdown-menu -->\r\n");
      out.write("                </div><!-- btn-group -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-group btn-group-list btn-group-messages\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                        <span class=\"badge\">2</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"dropdown-menu pull-right\">\r\n");
      out.write("                        <a href=\"\" class=\"link-right\"><i class=\"fa fa-plus\"></i></a>\r\n");
      out.write("                        <h5>新消息</h5>\r\n");
      out.write("                        <ul class=\"media-list dropdown-list\">\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <span class=\"badge badge-success\">New</span>\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user1.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Nusja Nawancali</strong>\r\n");
      out.write("                                    <p>Hi! How are you?...</p>\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-clock-o\"></i> 15 minutes ago</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <span class=\"badge badge-success\">New</span>\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user2.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Weno Carasbong</strong>\r\n");
      out.write("                                    <p>Lorem ipsum dolor sit amet...</p>\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-clock-o\"></i> July 04, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user3.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Venro Leonga</strong>\r\n");
      out.write("                                    <p>Do you have the time to listen to me...</p>\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-clock-o\"></i> July 03, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user4.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Nanterey Reslaba</strong>\r\n");
      out.write("                                    <p>It might seem crazy what I'm about to say...</p>\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-clock-o\"></i> July 03, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"media\">\r\n");
      out.write("                                <img class=\"img-circle pull-left noti-thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\resources\\images\\photos\\user1.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                    <strong>Nusja Nawancali</strong>\r\n");
      out.write("                                    <p>Hey I just met you and this is crazy...</p>\r\n");
      out.write("                                    <small class=\"date\"><i class=\"fa fa-clock-o\"></i> July 02, 2014</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"dropdown-footer text-center\">\r\n");
      out.write("                            <a href=\"\" class=\"link\">查看所有消息</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div><!-- dropdown-menu -->\r\n");
      out.write("                </div><!-- btn-group -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-group btn-group-option\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <ul class=\"dropdown-menu pull-right\" role=\"menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/profile.do\"><i class=\"glyphicon glyphicon-TUser\"></i> 个人档案</a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"glyphicon glyphicon-star\"></i> 活动日志</a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i> 账户设置</a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"glyphicon glyphicon-question-sign\"></i> 帮助</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/j_spring_security_logout\"><i class=\"glyphicon glyphicon-log-out\"></i>登出</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- btn-group -->\r\n");
      out.write("\r\n");
      out.write("            </div><!-- pull-right -->\r\n");
      out.write("\r\n");
      out.write("        </div><!-- header-right -->\r\n");
      out.write("\r\n");
      out.write("    </div><!-- headerwrapper -->\r\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
